GLOBAL_LIST_INIT(character_accents, list("No accent",
	"Dwarf accent",
	"Thick Dwarf accent",
	"Dark Elf accent",
	"Elf accent",
	"Grenzelhoft accent",
	"Hammerhold accent",
	"Proper Noble accent",
	"Half Orc accent",
	"Urban Orc accent",
	"Inzectoid accent",
	"gallant_replacement",
	"poor_replacement"))
