/datum/species/get_accent_list(mob/living/carbon/human/H, type)
	switch(H.char_accent)
		if("No accent")
			return
		if("Dwarf accent")
			return strings("tidi_dwarfcleaner_replacement.json", type, "tidi_strings")
		if("Thick Dwarf accent")
			return strings("tidi_dwarf_replacement.json", type, "tidi_strings")
		if("Dark Elf accent")
			return strings("tidi_french_replacement.json", type, "tidi_strings")
		if("Elf accent")
			return strings("tidi_russian_replacement.json", type, "tidi_strings")
		if("Grenzelhoft accent")
			return strings("tidi_german_replacement.json", type, "tidi_strings")
		if("Hammerhold accent")
			return strings("tidi_Anglish.json", type, "tidi_strings")
		if("Proper Noble accent")
			return strings("tidi_proper_replacement.json", type, "tidi_strings")
		if("Half Orc accent")
			return strings("tidi_middlespeak.json", type, "tidi_strings")
		if("Urban Orc accent")
			return strings("tidi_norf_replacement.json", type, "tidi_strings")
		if("Inzectoid accent")
			return strings("tidi_inzectoid_replacement.json", type, "tidi_strings")
		if("gallant_replacement")
			return strings("tidi_gallant_replacement.json", type, "tidi_strings")
		if("poor_replacement")
			return strings("tidi_poor_replacement.json", type, "tidi_strings")
